export interface WorkbookRoadmapEntry {
  sheet: string;
  stage: "PREGAME_INPUT" | "PROJECTION" | "DECISION" | "AUDIT" | "SETTLEMENT" | "REPLAY" | "META";
  timing: string;
  purpose: string;
  boardRelationship: string;
  readNote: string;
}

/**
 * Operator-facing registry for every workbook tab. A schema test requires exact
 * one-to-one coverage so newly added sheets cannot become undocumented pages.
 */
export const WORKBOOK_ROADMAP: WorkbookRoadmapEntry[] = [
  { sheet: "DAILY_MATCHUPS", stage: "PREGAME_INPUT", timing: "Every publish (Module 08)", purpose: "Game identity, probable pitchers, workloads, weather, park, prior outing, umpire, and market context.", boardRelationship: "Mirrors source evidence used by normalization and projection; it is not itself a spreadsheet-formula dependency.", readNote: "Start here to confirm the correct slate, starters, and obvious source gaps." },
  { sheet: "TODAY_LINEUPS", stage: "PREGAME_INPUT", timing: "Every publish (Module 08)", purpose: "Posted or projected batting orders with batter form and platoon context.", boardRelationship: "Module 09 uses the same lineup payload to calculate lineup factors before GAME_SUMMARY.", readNote: "Check official/projected status and coverage before trusting allocation." },
  { sheet: "TEAM_FORM_INPUT", stage: "PREGAME_INPUT", timing: "Every publish (Module 08)", purpose: "Recent team run-rate and form inputs used to establish offensive baselines.", boardRelationship: "Feeds Module 09 offense rates and therefore team and total projections.", readNote: "Audit when recent form appears to dominate a team allocation." },
  { sheet: "BULLPEN_USAGE_DAILY", stage: "PREGAME_INPUT", timing: "Every publish (Module 08)", purpose: "Reliever usage, availability, workload, and bullpen quality context.", boardRelationship: "Feeds Module 09 bullpen innings and continuation components.", readNote: "Read role importance and workload together; the Notes column is not durable." },
  { sheet: "RUN_ENVIRONMENT", stage: "PREGAME_INPUT", timing: "Every publish (Modules 08/09 environment resolver)", purpose: "Authoritative park, weather, roof, wind, certainty, run multiplier, and HR factor.", boardRelationship: "The same resolver and multiplier are consumed by Module 09; environment cannot originate a thesis.", readNote: "Check fallback, roof-pending, and weather-vehicle status before using an environmental edge." },
  { sheet: "ODDS_HISTORY", stage: "PREGAME_INPUT", timing: "Append on every publish (Module 05d)", purpose: "Time-stamped total snapshots; the earliest daily row is the opener.", boardRelationship: "Supplies movement context and line provenance; price remains downstream of baseball truth.", readNote: "Use for movement and stale-line diagnosis, not projection construction." },
  { sheet: "STATCAST_GAME_PREVIEW", stage: "PREGAME_INPUT", timing: "Every publish when Savant preview is available (Modules 02e/08b)", purpose: "Timestamped preview identity, pitcher metrics, hitter aggregates, availability, and parser warnings.", boardRelationship: "Does not directly alter the board; feeds the Statcast estimate audit and records preview availability in Decision Audit.", readNote: "Confirm identity, lineup status, timestamp, and missing fields before using it." },

  { sheet: "GAME_INTEGRATION", stage: "PROJECTION", timing: "Every publish (Module 09)", purpose: "Two rows per game—one per team—combining offense, opposing starter, bullpen, lineup, and environment.", boardRelationship: "Feeds the team allocations summarized in GAME_SUMMARY.", readNote: "Use when the total seems plausible but the away/home split looks wrong." },
  { sheet: "GAME_SUMMARY", stage: "PROJECTION", timing: "Every publish (Module 09)", purpose: "One-row game projection with away runs, home runs, total, components, environment, and lineage.", boardRelationship: "Primary projection input to Module 11 and SLATE_BOARD.", readNote: "Traffic_Conversion_Runs and HR_XBH_Damage_Runs remain inactive zeros; read their estimates in STATCAST_SHADOW_AUDIT." },
  { sheet: "PLAYER_INTEGRATION", stage: "PROJECTION", timing: "Every publish (Module 09)", purpose: "Per-batter lineup identity, opponent, environment, available statistics, and explicit gaps.", boardRelationship: "Audit lineage for lineup factors; it does not independently authorize a board decision.", readNote: "Use for player-level identity and missing-stat debugging." },
  { sheet: "STATCAST_SHADOW_AUDIT", stage: "PROJECTION", timing: "Every publish after GAME_SUMMARY (Module 09s)", purpose: "Starter xwOBA plus estimated traffic and HR/XBH tail adjustments, with primary and sensitivity low-center challengers and an upper-tail band.", boardRelationship: "Supplies the tentative decision range and a manual low-center risk warning; it never replaces the active Module 09 total or creates authorization.", readNote: "Compare Current_Projection with Estimated_Projection; when Low_Center_Volatility_Flag is set, inspect both challengers, upper-tail band, and reason tags as distribution evidence only." },
  { sheet: "LOW_CENTER_CALIBRATION_HISTORY", stage: "AUDIT", timing: "Append every pregame Module 09s run for low-center games", purpose: "Durable timestamped capture of the base, +1.50 primary, and +2.00 sensitivity candidates.", boardRelationship: "No board input. It prevents settlement from recreating or backdating a candidate.", readNote: "Use the latest row strictly before Scheduled_First_Pitch; later or invalid snapshots are not prospective evidence." },
  { sheet: "LOW_CENTER_CALIBRATION_REPORT", stage: "SETTLEMENT", timing: "Every settlement after final scores arrive", purpose: "Per-game base-versus-challenger error comparison from preserved prospective candidates.", boardRelationship: "No board input. This is the promotion evidence for low-center calibration only.", readNote: "Compare Base_Abs_Error, Primary_Abs_Error, and Sensitivity_Abs_Error; do not promote a challenger from isolated results." },
  { sheet: "STARTER_SURVIVAL_CALIBRATION_HISTORY", stage: "AUDIT", timing: "Every pre-first-pitch Module 09t run", purpose: "Timestamped four-state starter survival/failure branch totals, probabilities, and continuous FDS diagnostics.", boardRelationship: "No board input. It is visible evidence for manual review only and cannot change projection, vehicle, market, or authorization.", readNote: "Only a snapshot strictly before Scheduled_First_Pitch is prospective. p = clamp(Projected_Starter_Innings / 9, 0, 1) is a temporary shadow default." },
  { sheet: "STARTER_SURVIVAL_CALIBRATION_REPORT", stage: "SETTLEMENT", timing: "Every settlement after actuals arrive", purpose: "Base-versus-SSAT error, market-direction, actual starter workload, and survival grading from preserved snapshots.", boardRelationship: "No board input. It measures the challenger without backfilling it.", readNote: "Read Base_Abs_Error beside SSAT_Abs_Error and actual starter survival results; no coefficient or threshold is promoted from one slate." },

  { sheet: "SLATE_INPUT", stage: "DECISION", timing: "Seeded/refreshed every publish (Module 10)", purpose: "Pipeline score inputs plus operator-owned vehicle, line, odds, notes, overrides, and frozen market fields.", boardRelationship: "Direct decision input to Module 11. Operator edits only O–W; authoritative pregame fields are pipeline-owned.", readNote: "Authoritative_Pregame_Total outranks the display/live Line after freeze." },
  { sheet: "SLATE_BOARD", stage: "DECISION", timing: "Every publish for still-mutable games (Module 11)", purpose: "Full current-slate decision output, scores, projection, market comparison, blockers, survival gate, and lock state.", boardRelationship: "This is the complete decision board.", readNote: "Read Projection, line, tentative range, Decision, blocker, lock status, and lineage together." },
  { sheet: "ACTIVE_BOARD_SNAPSHOT", stage: "DECISION", timing: "Every publish (Module 11)", purpose: "Condensed view of currently authorized board entries.", boardRelationship: "Filtered operational view of SLATE_BOARD; it does not create authorization.", readNote: "Use for quick execution only after verifying the full board and lock state." },
  { sheet: "BOARD_LOCK_STATE", stage: "AUDIT", timing: "Created/updated per game at lock (Module 11)", purpose: "Immutable record of the single authoritative final authorization and lock provenance.", boardRelationship: "Records the board decision; it must never calculate an independent decision.", readNote: "Use to resolve any disagreement between displayed decision surfaces." },
  { sheet: "VEHICLE_LOG", stage: "AUDIT", timing: "Published/frozen after Module 11 (Module 17 phase 1)", purpose: "Immutable prospective vehicle, projection, market line, direction, and decision record.", boardRelationship: "Freezes what SLATE_BOARD actually published for later settlement.", readNote: "This—not a later recalculation—is the historical prediction source." },
  { sheet: "DECISION_AUDIT_LOG", stage: "AUDIT", timing: "Pregame update/freeze on publish; settlement append later (Module 20)", purpose: "Model state, manual overlay, reasoning source, authorization, result, and independent grading.", boardRelationship: "Consumes the authoritative decision; tracks why it was authorized or passed.", readNote: "OPEN fields may update; frozen pregame fields must not change after lock." },

  { sheet: "SHADOW_VALIDATION", stage: "AUDIT", timing: "Every publish after Module 09 (Module 12s)", purpose: "Current-slate repaired-versus-legacy projection comparison.", boardRelationship: "Validation only; no authorization influence.", readNote: "Use to detect unexpected projection drift during commissioning." },
  { sheet: "SHADOW_HISTORY", stage: "AUDIT", timing: "Append on every publish (Module 12s)", purpose: "Historical accumulation of SHADOW_VALIDATION snapshots.", boardRelationship: "No direct board influence; preserves commissioning change history.", readNote: "Use for time-series drift, not the current executable board." },
  { sheet: "RUN_LOG", stage: "AUDIT", timing: "Append at the end of every publish (Module 12)", purpose: "Run ID, schema, module status, counts, validation, errors, warnings, and source observability.", boardRelationship: "Certifies whether the board-producing run completed semantically.", readNote: "Read first after every workflow; a green workflow is insufficient if this row is partial or stale." },

  { sheet: "SHADOW_OUTCOMES", stage: "SETTLEMENT", timing: "Daily settlement (Module 14)", purpose: "One row per game with frozen projection, final score, errors, direction, and pitcher provenance.", boardRelationship: "Grades the preserved prospective board state without rerunning it.", readNote: "Primary settled truth table; verify projection source is frozen/published." },
  { sheet: "PROJECTION_REPLAY", stage: "SETTLEMENT", timing: "Daily settlement (Module 14)", purpose: "Frozen-published projection replay against actual results.", boardRelationship: "Measures the board that existed pregame, not a repaired postgame estimate.", readNote: "Use for per-game error and frozen-versus-repaired comparison." },
  { sheet: "VEHICLE_POSTMORTEM", stage: "SETTLEMENT", timing: "After outcomes (Module 17 phase 2)", purpose: "Ticket, thesis, capture, blocker, and failure/survival grading by game.", boardRelationship: "Grades the selected vehicle and authorization separately from the raw projection.", readNote: "A push is neutral and a passed winner is not automatically a bad pass." },
  { sheet: "SURVIVAL_GATE_REPLAY", stage: "SETTLEMENT", timing: "Settlement/replay (Module 18)", purpose: "Re-grades Over candidates through the component survival floor with provenance.", boardRelationship: "Audits one authorization gate; it does not rewrite the historical board.", readNote: "Use to separate environment-manufactured Overs from baseball-supported Overs." },
  { sheet: "STARTER_AUDIT", stage: "SETTLEMENT", timing: "After settlement (Module 16)", purpose: "Starter-level projection accuracy and provenance summary.", boardRelationship: "Learning surface only; starters cannot independently define game truth.", readNote: "Compare survival and failure paths across samples, not one result." },
  { sheet: "REGRESSION_REPORT", stage: "SETTLEMENT", timing: "After settlement or explicit regression run (Module 15)", purpose: "MAE, median error, bias, miss rate, over/under projection rates, and windows.", boardRelationship: "Controls evidence about model reliability; does not rewrite a prior board.", readNote: "Separate total accuracy from allocation and direction before tuning." },
  { sheet: "MONOTONICITY", stage: "SETTLEMENT", timing: "With regression report (Module 15)", purpose: "Tests whether larger frozen projection edges produce better directional results by side and tier.", boardRelationship: "Authorization governance reads its verdict; low samples must fail closed.", readNote: "Check sample size before trusting a PASS verdict." },

  { sheet: "REPLAY_RESULTS", stage: "REPLAY", timing: "Explicit historical replay only (Module 13)", purpose: "Date-anchored baseline-versus-candidate game results with historical environment provenance.", boardRelationship: "Offline candidate evaluation; never substitutes for a prospective board record.", readNote: "Missing historical weather must remain flagged and neutral." },
  { sheet: "REPLAY_METRICS", stage: "REPLAY", timing: "Each historical replay (Module 13)", purpose: "Aggregate metrics for baseline and candidate variants, including calibration and direction where lines exist.", boardRelationship: "Supports commissioning decisions, not game authorization.", readNote: "Compare variants on multiple metrics and bands, not MAE alone." },

  { sheet: "SCHEMA_REFERENCE", stage: "META", timing: "Schema repair/settlement documentation step", purpose: "Generated column dictionary with type, format, ownership, and description.", boardRelationship: "Documentation only.", readNote: "Use when a column name or ownership rule is unclear." },
  { sheet: "README", stage: "META", timing: "Schema repair/settlement documentation step", purpose: "Workbook orientation, schema version, quick read order, roadmap summaries, and operating cautions.", boardRelationship: "Documentation only.", readNote: "Start here when returning after time away." },
];

export function buildWorkbookRoadmapReadmeRows(): string[][] {
  return WORKBOOK_ROADMAP.map((entry) => [
    `Tab_${entry.sheet}`,
    `${entry.stage} | ${entry.timing} | ${entry.purpose} Board: ${entry.boardRelationship} Read: ${entry.readNote}`,
  ]);
}
